### ISSUE TITLE
MVCGrid Filter, Paging, CSV Export Not Work In Partial View When Get From Ajax

### ISSUE THREAD

**Issue by ajayvpatelce** [joeharrison714/MVCGrid.Net#12]
Hello,

MVCGrid Filter, Paging, CSV Export not work In Partial View get from Ajax. 
Shorting Works perfectly.

http://www.filedropper.com/mvcgridnet-master
Download this code.
In this code one demo example created in your demo menu 'Filter Ajax'.

**Comment by joeharrison714** [comment]
Try calling `MVCGrid.init()` in javascript after loading the grid from ajax

**Comment by ajayvpatelce** [comment]
Thanks.
