### ISSUE TITLE
WithClientSideLoadingCompleteFunctionName and WithClientSideLoadingMessageFunctionName Don't Terminate Properly

### ISSUE THREAD

**Issue by biclon** [joeharrison714/MVCGrid.Net#15]
WithClientSideLoadingCompleteFunctionName and WithClientSideLoadingMessageFunctionName don't terminate properly. When these methods are called the loading dialog fails to disappear off the screen.

**Comment by joeharrison714** [comment]
This was fixed with biclon's pull request
