### ISSUE TITLE
Country specific characters are replaced by ?? in first show of the grid

### ISSUE THREAD

**Issue by januszj** [joeharrison714/MVCGrid.Net#21]
Hi,
First want to thank you for the well working grid solution for MVC :)
I liked especially possibility to modify grids rendering using interface!

Issue I have is that when grid is displayed first time it replace special country characters (in this case Polish) with ??.
When Grid is refreshed using paging link or global search, the characters become correct.

Here is example:
![image](https://cloud.githubusercontent.com/assets/1262428/8871441/9638f19a-31f5-11e5-9a1c-03871b559cc0.png)

**Comment by joeharrison714** [comment]
Thanks for your report. I will be looking into it. Can you give me an example of what characters specifically are getting changed in this way?

**Comment by januszj** [comment]
Hi Joe,
Here are examples of Polish characters that get changed: ńłóźćłąę.
KR,
Janusz

**Comment by joeharrison714** [comment]
Janusz,
This has been fixed. Please update your nuget package. The problem was on first load, I was using ASCII encoding, and it had to be changed to UTF8.
Thanks,
Joe
