### ISSUE TITLE
 The type or namespace name 'Web' does not exist in the namespace 'MVCGrid' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by iamchamith** [joeharrison714/MVCGrid.Net#33]
I Was configure MVCGrid to my mvc application using the tutorial.
application building successfully,
but when run the application there is a error message show as below.
 The type or namespace name 'Web' does not exist in the namespace 'MVCGrid' (are you missing an assembly reference?)
do you have any idea to fix it ?
Thank you.

**Comment by joeharrison714** [comment]
Hi @iamchamith,
What version of MVC are you using?
Thanks,
Joe
