### ISSUE TITLE
Sorting has issue

### ISSUE THREAD

**Issue by Sopheakmorm** [joeharrison714/MVCGrid.Net#48]
query = query.OrderBy(p => p.FormName, options.SortDirection);
It doesn't support with opention.SortDirection
"mvcgrid.models.sortdirection is not assignable to parameter type system.collection generic.icomparer<string>"
I could not use this statement to sort my data in grid.

**Comment by shefaliA** [comment]
Try to use query = query.OrderBy(p => p.FormName); it works

**Comment by mrlovre** [comment]
do `query = options.SortDirection == SortDirection.Asc ? query.OrderBy(p => p.FormName) : query.OrderByDescending(p => p.FormName);` instead.
