### ISSUE TITLE
How to use HTML Input checkbox in column header?

### ISSUE THREAD

**Issue by ajayvpatelce** [joeharrison714/MVCGrid.Net#6]
I want to use html format <input type='checkbox'> in column header. How to configure grid column?

**Comment by bigjoe714** [comment]
You can currently put HTML in a column header by using the HeaderText property of the column, however I just tried it with a checkbox and the click event was intercepted for sorting so the checkbox would not check.

You could create your own razor view and add the checkboxes that way. Here are instructions on how to do that:
http://localhost:57178/demo/customrazorview

If you could tell me more about what you are trying to do I may be able to help further.

**Comment by ajayvpatelce** [comment]
Thanks for reply,

Column Configuration Code:                                        
cols.Add("Delete")
      .WithHtmlEncoding(false)
      .WithSorting(false)
      .WithFiltering(false)
      .WithHeaderText("<input type='checkbox' id='chkselectall'>")
      .WithValueExpression((p, c) => c.UrlHelper.Action("Save", "Country", new { area = "General", id = p.CountryID }))
      .WithValueTemplate("<input type='checkbox' class='select' value='{Model.CountryID}'>")
      .WithPlainTextValueExpression((p, c) => "");

All things works perfectly just not working paging selection & global search.
If I remove column header text or put plain text instead of HTML input tag,  all things work perfectly include paging selection & global search.

**Comment by joeharrison714** [comment]
I am trying to reproduce your issue but so far am unable to do so.  What does it do when you try to change pages or do global search? Are there any errors in the browser console?
Can you include any additional javascript tied to the chkselectall?

**Comment by ajayvpatelce** [comment]
Give me browser error when page load 
Chrome: 'Uncaught SyntaxError: Unexpected token c'
Firefox SyntaxError: 'JSON.parse: expected ',' or '}' after property value in object at line 1 column 182 of the JSON data'
IE: Invalid character
File: jquery-1.11.2.min.js, Line: 4, Column: 15934

Yes I include additional js for chkselectall.

**Comment by joeharrison714** [comment]
Can you post the js you are using for chkselectall?

**Comment by ajayvpatelce** [comment]
```js
$(function () {
    //Multi Select
    $('.select').click(function () {
        $('#btnDelete').addClass('disabled');
        $('.select:checked').each(function () {
            $('#btnDelete').removeClass('disabled');
        });
    });

    $('#chkselectall').click(function (e) {
        //alert('test');
        if ($(this).is(':checked')) {
            //alert('test');
            $('.select').each(function () {
                $(this).prop('checked', true);
                $('#btnDelete').removeClass('disabled');
            });
        }
        else {
            $('.select').each(function () {
                $(this).prop('checked', false);
                $('#btnDelete').addClass('disabled');
            });
        }
    });
});
```

**Comment by joeharrison714** [comment]
Hi again,
I am still trying to reproduce the issue. Take a look here:
http://mvcgrid.net/Test/Issue6

It seems to be working the way you want. Can you spot any differences?  Perhaps is something in your data.
Thanks,
Joe

**Comment by ajayvpatelce** [comment]
Thanks for reply,

I want this but just add global search or filter and check its work perfectly or not?

**Comment by joeharrison714** [comment]
ok, i think i got it!  There was a javascript encoding issue once I tried to do filtering with a grid that had a column with html header.  This should now be fixed, and the nuget package has been updated. Please try it out and let me know what happens. Thanks for finding the bug!

**Comment by ajayvpatelce** [comment]
Its Ok and thanks for reply.

**Comment by ajayvpatelce** [comment]
Thanks for support, Now works perfectly.

**Comment by colinchin** [comment]
hi,

when the checkall box is checked, and I uncheck 1 of the checkbox, the checkall box won't uncheck.

Can you let me know how to do this in the jQuery?

**Comment by colinchin** [comment]
hi,

also, if I manually check all checkboxes in the grid, the checkall box will not be checked.

Can you also post the jQuery script to do this?

**Comment by colinchin** [comment]
I do it this way:
@section scripts{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <script type="text/javascript">
        $("[id=chkselectall]").live("click", function () {
            var chkHeader = $(this);
            var grid = $(this).closest("table");
            $("input[type=checkbox]", grid).each(function ()
            {
                if (chkHeader.is(":checked"))
                {
                    $(this).attr("checked", "checked");
                    $("td", $(this).closest("tr")).addClass("selected");
                    $('#btnApprove').removeClass('disabled');
                }
                else
                {
                    $(this).removeAttr("checked");
                    $("td", $(this).closest("tr")).removeClass("selected");
                    $('#btnApprove').addClass('disabled');
                }
            });
        });
        $("[id=chkselect]").live("click", function ()
        {
            var grid = $(this).closest("table");
            var chkHeader = $("[id=chkselectall]", grid);
            if (!$(this).is(":checked"))
            {
                $("td", $(this).closest("tr")).removeClass("selected");
                chkHeader.removeAttr("checked");
            }
            else
            {
                $("td", $(this).closest("tr")).addClass("selected");
                if ($("[id=chkselect]", grid).length == $("[id=chkselect]:checked", grid).length)
                {
                    chkHeader.attr("checked", "checked");
                }
            }
            $("input[type=checkbox]", grid).each(function () {
                var valid = false;
                if ($(this).is(':checked'))
                {
                    valid = true;
                }
                if (valid)
                    $('#btnApprove').removeClass('disabled');
                else
                    $('#btnApprove').addClass('disabled');
            });
        });
    </script>
}
