### ISSUE TITLE
use globalization for HeaderText

### ISSUE THREAD

**Issue by shrdshrd** [joeharrison714/MVCGrid.Net#68]
Globalization does not work for HeaderText in mvcgrid.config
how can i use Resources files for  HeaderText?

**Comment by TareqAgha** [comment]
Hello shrdshrd  you found a solution to the problem?

**Comment by henryroach** [comment]
Hi, did someone find any solution? :-)

**Comment by joeharrison714** [comment]
I just merged in #35 which added the ability to customize the text in the configuration.
