### ISSUE TITLE
export to spss

### ISSUE THREAD

**Issue by reza-sed** [joeharrison714/MVCGrid.Net#92]
Hi there,
I want to add SPSS export to MVCGrid.
please help
thanks in advance

**Comment by joeharrison714** [comment]
Hi,
Did you take a look at this?
http://mvcgrid.net/demo/customexport

I am not familiar with the SPSS format but if you know how to build the format in code it shouldn't be too difficult. See here for an example I have of a tab-delimited format:
https://github.com/joeharrison714/MVCGrid.Net/blob/master/MVCGridExample/Models/TabDelimitedRenderingEngine.cs

**Comment by reza-sed** [comment]
Thank you
I have done it by using pre render method
